# Load in `Numpy`
***

In [2]:
import numpy as np

# The Basics 
***

In [14]:
# Interger array
a = np.array([1,2,3], dtype='int32')
print(a)
a

[1 2 3]


array([1, 2, 3])

In [15]:
# Float array
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [16]:
# Get Dimension
print(a.ndim)
print(b.ndim)

1
2


In [17]:
# Get shape
print(a.shape) # 1D that's why blank space
print(b.shape)

(3,)
(2, 3)


In [18]:
# Get type
print(a.dtype)
print(b.dtype)

int32
float64


In [28]:
# Get Size in bytes
print(a.itemsize)
print(b.itemsize)

4
8


In [29]:
# Get Total items in array
print(a.size)
print(b.size)

3
6


In [30]:
# Total size in bytes
print(a.nbytes)
print(b.nbytes)

12
48


# Accessing/Changing specific elements, rows, columns, etc...
***

In [20]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [4]:
# Get specific element [r,c]
print(a[1,5], a[1,-2])

13 13


In [5]:
# Get a Specific Row
print(a[0, :])

[1 2 3 4 5 6 7]


In [6]:
# Get a specific Column
print(a[:, 2])

[ 3 10]


In [10]:
# Using stepsize
print(a[0, 1:-1:2])

[2 4 6]


In [13]:
# 3D Array
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)
print(b.ndim)
print(b[:1:])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
[[[1 2]
  [3 4]]]


# Initializing Different Types of Array 

In [15]:
# All 0's matrix
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
# All 1's matrix
np.ones((5,4), dtype='int32')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [18]:
# Any Number
np.full((4,3), 100)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [22]:
# Any other Number full_like
np.full_like(a, 101)

array([[101, 101, 101, 101, 101, 101, 101],
       [101, 101, 101, 101, 101, 101, 101]])

In [23]:
# Any Other NUmber using full
np.full(a.shape, 101)

array([[101, 101, 101, 101, 101, 101, 101],
       [101, 101, 101, 101, 101, 101, 101]])

In [28]:
#Random Decimal Number
print(np.random.rand(4,2,3))
print(np.random.random_sample(a.shape))

[[[0.66972082 0.03816368 0.75389912]
  [0.51144318 0.33942583 0.34944263]]

 [[0.63190246 0.92379037 0.63668074]
  [0.23333524 0.16612176 0.92463974]]

 [[0.28691703 0.65873233 0.85514941]
  [0.86867795 0.01365209 0.61082524]]

 [[0.64014969 0.64982455 0.35518841]
  [0.73270746 0.61986617 0.03930304]]]
[[0.71569496 0.0037102  0.43761134 0.29547695 0.82564025 0.25897718
  0.20700078]
 [0.31275979 0.13781135 0.98433209 0.61028813 0.20678479 0.30733147
  0.79053499]]


In [3]:
# Random interger value
#Start value = 0, End value = 10
np.random.randint(10, size=(4,3))

array([[1, 0, 2],
       [0, 0, 5],
       [0, 9, 3],
       [3, 3, 7]])

In [4]:
# Indentity Matrix
c = np.identity(4, dtype='int16')
print(c)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [7]:
# Repeating the value of by n times
np.repeat(c, 3, axis=0)

array([[1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1]], dtype=int16)

In [43]:
# Pattern
x = np.ones((5,5), dtype='int16')
y = np.zeros((3,3), dtype='int16')
y[1,1] = 9

x[1:-1,1:-1] = y
print(x)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [48]:
# Copying Array
d = c.copy()
d[0,1] = 100
print(c)
print(d)

[[1 0]
 [0 1]]
[[  1 100]
 [  0   1]]


# Mathematics

In [49]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [50]:
# Add 2
a + 2

array([3, 4, 5, 6])

In [51]:
# Sub 2
a - 2

array([-1,  0,  1,  2])

In [55]:
# Mul 2
a * 2

array([2, 4, 6, 8])

In [56]:
# Div 2
a / 2

array([0.5, 1. , 1.5, 2. ])

In [57]:
# Add two array
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [58]:
# power of array
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [59]:
# Sin of array
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# Linear Algebra

In [65]:
# Matrix Multiplication
a = np.ones((2,3), dtype='int32')
print(a)
b = np.full((3,2), 2)
print(b)

print(np.matmul(a,b))
print(a.dot(b))

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]
[[6 6]
 [6 6]]
[[6 6]
 [6 6]]


In [67]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

# Statistics 

In [70]:
# stats = np.arange(1,7).reshape(2,3)
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
# Minimum of array
np.min(stats)

1

In [72]:
np.max(stats, axis=1)

array([3, 6])

In [74]:
np.sum(stats, axis=0)

array([5, 7, 9])

# Reorganizing Array 

In [8]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
after = before.reshape((1,8))
print(after)
after = before.reshape((2,2,2))
print(after)

[[1 2 3 4 5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
#Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(np.vstack([v1,v1]))
print(np.vstack([v1,v2]))

[[1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4]
 [5 6 7 8]]


In [16]:
#Horizontal Stack
print(np.hstack([v1,v2]))
print(np.hstack([v1,v1]))

[1 2 3 4 5 6 7 8]
[1 2 3 4 1 2 3 4]


# Miscellaneous 

### Load Data from File

In [20]:
data = np.genfromtxt('4_data.txt', delimiter=',', dtype='int16')
print(data)
print(data.astype('float64'))

[[ 1  2  3  4  5  6  7  8  9]
 [11 12 13 14 15 16 17 18 19]
 [21 22 23 24 25 26 27 28 29]]
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29.]]


### Boolean Masking and Advanced Indexing  

In [23]:
#Return True if condtion is true
data > 20

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [24]:
#Return data if condition is true
data[data > 20]

array([21, 22, 23, 24, 25, 26, 27, 28, 29], dtype=int16)

In [26]:
#Index list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [31]:
#Checking Columnwise data
np.any(data > 20, axis=0)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [32]:
#Checking Rowwise data
np.all(data > 20, axis=1)

array([False, False,  True])

In [35]:
#Multiple Condition
print(((data > 10) & (data < 20)))
print((~((data > 10) & (data < 20))))

[[False False False False False False False False False]
 [ True  True  True  True  True  True  True  True  True]
 [False False False False False False False False False]]
[[ True  True  True  True  True  True  True  True  True]
 [False False False False False False False False False]
 [ True  True  True  True  True  True  True  True  True]]


# Pattern
![Pattern](4_pattern.png)

In [39]:
p = np.arange(1,31).reshape(6,5)
print(p)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [44]:
#Blue
p[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [45]:
#Green
p[[0,1,2,3], [1,2,3,4]]

array([ 2,  8, 14, 20])

In [46]:
#Red
p[[0,4,5], 3:5]

array([[ 4,  5],
       [24, 25],
       [29, 30]])