# Introduction of NumPy

In [1]:
# Importing Numpy
import numpy as np

In [27]:
#Create Array
a = np.array([1,2,3])
print("Type of variable a is", type(a))
print("Values in a is", a)
print("Total Number of element in the array =", a.size)
print("Value at index 0 is",a[0])
print("Dimension of array a is", a.ndim)

Type of variable a is <class 'numpy.ndarray'>
Values in a is [1 2 3]
Total Number of element in the array = 3
Value at index 0 is 1
Dimension of array a is 1


In [84]:
#Multidimensional Array
b = np.array([[1,2], [3,4], [5,6]])
print(a.size)
print("Values in b is", b)
print("Value at index 0,1 is",b[0][1])
print("Dimension of array b is", b.ndim)
print("Data Type of Array b =", b.dtype)
print("Size of Each Element in Array b =", b.itemsize) 

9
Values in b is [[1 2]
 [3 4]
 [5 6]]
Value at index 0,1 is 2
Dimension of array b is 2
Data Type of Array b = int32
Size of Each Element in Array b = 4


In [29]:
#Float array
c = np.array([[1,2], [3,4], [5,6]], dtype=np.float64)
print(c)
print(c.dtype)
print("Total Number of element in the array =", c.size)
print("Shape of array (Rows, columns) =", c.shape)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
float64
Total Number of element in the array = 6
Shape of array (Rows, columns) = (3, 2)


In [30]:
# Complex Array
c = np.array([[1,2], [3,4], [5,6]], dtype=complex)
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]]


In [37]:
#Initializing array with zeros and one
print(np.zeros((3,4)))
print(np.ones((2,4)))

#Array of continuous number
print(np.arange(1,10))

#Array with a gap of 5
print(np.arange(5,100,5))

#Array of linerly space element 
#15 element equally space between 1 to 4 (inclusive)
print(np.linspace(1,4,15))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1 2 3 4 5 6 7 8 9]
[ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[1.         1.21428571 1.42857143 1.64285714 1.85714286 2.07142857
 2.28571429 2.5        2.71428571 2.92857143 3.14285714 3.35714286
 3.57142857 3.78571429 4.        ]


In [64]:
d = np.array([[7,8], [9,1], [2,3]])
print("Shape of array =",d.shape)

#Changing shape of array
# Didn't save the changes on the original array
print("New shaped array =",d.reshape(2,3))
print("New shaped array =",d.reshape(1,6))

#Displaying array in 1D
print("Array in 1D =", d.ravel())

Shape of array = (3, 2)
New shaped array = [[7 8 9]
 [1 2 3]]
New shaped array = [[7 8 9 1 2 3]]
Array in 1D = [7 8 9 1 2 3]


In [65]:
#Maths operation on array
print("Array >>>\n", d)
print("Minimum = ", d.min())
print("Maximum =", d.max())
print("Sum =", d.sum())
print("Sum (Column) =", d.sum(axis=0))
print("Sum (Row) =", d.sum(axis=1))
print("Square Root =", np.sqrt(d))
print("Standard Deviation =", np.std(d))

Array >>>
 [[7 8]
 [9 1]
 [2 3]]
Minimum =  1
Maximum = 9
Sum = 30
Sum (Column) = [18 12]
Sum (Row) = [15 10  5]
Square Root = [[2.64575131 2.82842712]
 [3.         1.        ]
 [1.41421356 1.73205081]]
Standard Deviation = 3.1091263510296048


In [79]:
e = np.array([[1,2,3],[4,5,6]])
print(e.shape)

(2, 3)


In [82]:
print("Array b shape =", b.shape)
print("Array d shape =", d.shape)
print("Array e shape =", e.shape)
print("Add >>>\n", b+d)
print("Sub >>>\n", b-d)
print("Mul >>>\n", b*d)
print("Div >>>\n", b/d)
print("Matrix Product >>>\n", b.dot(e))

Array b shape = (3, 2)
Array d shape = (3, 2)
Array e shape = (2, 3)
Add >>>
 [[ 8 10]
 [12  5]
 [ 7  9]]
Sub >>>
 [[-6 -6]
 [-6  3]
 [ 3  3]]
Mul >>>
 [[ 7 16]
 [27  4]
 [10 18]]
Div >>>
 [[0.14285714 0.25      ]
 [0.33333333 4.        ]
 [2.5        2.        ]]
Matrix Product >>>
 [[ 9 12 15]
 [19 26 33]
 [29 40 51]]


# Slicing of Array 

In [138]:
a = np.array([[6,7,8], [1,2,3], [9,2,3]])
print(a)

[[6 7 8]
 [1 2 3]
 [9 2 3]]


In [97]:
print("Element at index [1,2] =", a[1][2], a[1,2]) # Both have same meaning
print("From row 0 and 1 and column 2 =", a[0:2,2]) # in term of index (0:2 - is slicing)
print("Value at index -1 =", a[-1], a[-1, 0:2], a[-1, -1])
print("All row and 1 & 2 column =", a[:,1:3]) # In term of index

Element at index [1,2] = 3 3
From row 0 and 1 and column 2 = [8 3]
Value at index -1 = [9 2 3] [9 2] 3
All row and 1 & 2 column = [[7 8]
 [2 3]
 [2 3]]


### Iterating through array

In [99]:
# one row at a time
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 2 3]


In [140]:
# One element at a time
for cell in a.flat:
    print(cell)
    
for cell in a.flatten():
    print(cell)
    

6
7
8
1
2
3
9
2
3
6
7
8
1
2
3
9
2
3


* `flatten` always returns a copy. <br>
***
* `ravel` returns a view of the original array whenever possible. This isn't visible in the printed output, but if you modify the array returned by ravel, it may modify the entries in the original array. If you modify the entries in an array returned from flatten this will never happen. ravel will often be faster since no memory is copied, but you have to be more careful about modifying the array it returns. <br>
***
* `reshape((-1,))` gets a view whenever the strides of the array allow it even if that means you don't always get a contiguous array.

### Stacking of array

In [103]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
print(a)
print(b)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [105]:
print(np.vstack((a,b))) # add element vertically
print(np.hstack((a,b))) # element added horizontally

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


### Slicing a array 

In [107]:
a = np.arange(1,31).reshape(2,15)
print(a)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]]


In [114]:
print(np.hsplit(a,3))
new = np.hsplit(a,3)
print(new[0])
print(new[1])
print(new[2])

[array([[ 1,  2,  3,  4,  5],
       [16, 17, 18, 19, 20]]), array([[ 6,  7,  8,  9, 10],
       [21, 22, 23, 24, 25]]), array([[11, 12, 13, 14, 15],
       [26, 27, 28, 29, 30]])]
[[ 1  2  3  4  5]
 [16 17 18 19 20]]
[[ 6  7  8  9 10]
 [21 22 23 24 25]]
[[11 12 13 14 15]
 [26 27 28 29 30]]


In [118]:
print(np.vsplit(a,2))
new = np.vsplit(a,2)
print(new[0])
print(new[1])

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]), array([[16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])]
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]
[[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]]


### array as index of array

In [133]:
a = np.arange(1,13).reshape(3,4)
print(a)
b = a > 4
# This will store true and false value
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [134]:
print(a[b])

[ 5  6  7  8  9 10 11 12]


In [135]:
print(a)
a[b]=-1
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


### Nditer function

In [156]:
a = np.arange(1,10).reshape(3,3)

# Print Row by row
for x in np.nditer(a, order='C'):
    print(x)

1
2
3
4
5
6
7
8
9


In [157]:
#Fortan Order
# Print column by column
for x in np.nditer(a, order='F', flags = ['external_loop']):
    print(x)

[1 4 7]
[2 5 8]
[3 6 9]


In [158]:
#Changing the value of array
for x in np.nditer(a, op_flags= ['readwrite']):
    x[...] = x*x
a

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [169]:
#NOTE
# to do this 
# 1. Same shape
# 2. One dimension any one array is 1
#parsing through two array 
print(a.shape)
print(b.shape)
b = np.arange(3,15,4).reshape(3,1)
for x,y in np.nditer([a,b]):
    print(x,y)

(3, 3)
(3, 1)
1 3
4 3
9 3
16 7
25 7
36 7
49 11
64 11
81 11
